"""Add content type and tone fields

Revision ID: 2327ab4bdcf8
Revises: 840571b04a79
Create Date: 2025-10-09 16:17:41.465558+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2327ab4bdcf8'
down_revision: Union[str, None] = '840571b04a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types
    contenttone_enum = sa.Enum('PROFESSIONAL', 'CASUAL', 'EDUCATIONAL', 'PROMOTIONAL', 'INSPIRATIONAL', name='contenttone')
    contenttype_enum = sa.Enum('POST', 'THREAD', 'ARTICLE', 'STORY', name='contenttype')
    
    contenttone_enum.create(op.get_bind(), checkfirst=True)
    contenttype_enum.create(op.get_bind(), checkfirst=True)
    
    # Add columns
    op.add_column('content', sa.Column('tone', contenttone_enum, nullable=True, server_default='PROFESSIONAL'))
    op.add_column('content', sa.Column('hashtags', sa.Text(), nullable=True))
    
    # Alter content_type column
    op.execute("ALTER TABLE content ALTER COLUMN content_type TYPE contenttype USING content_type::text::contenttype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE content ALTER COLUMN content_type TYPE varchar USING content_type::text")
    op.drop_column('content', 'hashtags')
    op.drop_column('content', 'tone')
    
    # Drop enum types
    sa.Enum(name='contenttype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='contenttone').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
