"""Add description and strategy_data to strategies

Revision ID: 840571b04a79
Revises: 912583be517b
Create Date: 2025-10-09 15:30:12.938043+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840571b04a79'
down_revision: Union[str, None] = '912583be517b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('strategies', sa.Column('strategy_data', sa.JSON(), nullable=True))
    op.add_column('strategies', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'status')
    op.drop_column('strategies', 'strategy_data')
    op.drop_column('strategies', 'description')
    # ### end Alembic commands ###
